version: 2
project_name: faucet

before:
  hooks:
    - go mod tidy

builds:
  - id: faucet
    main: ./cmd/faucet
    binary: faucet
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - name: faucet
    repository:
      owner: faucetdb
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://faucet.dev"
    description: "Turn any database into a secure REST API. One binary. One command."
    license: "MIT"
    install: |
      bin.install "faucet"
    test: |
      system "#{bin}/faucet", "version"
